---
services:
    backend:
        container_name: slide_merger_backend
        image: docker.io/nicolasgrosjean38/slide_merger_backend:0.0.1
        user: 0:0   # TODO Fix volume mount write permission issue to remove this
        environment:
          - HOST=0.0.0.0
          - ROOT_DATA_DIRECTORY=/data
        networks:
          - backend_network
        ports:
          - 8899:8899
        volumes:
          - ./data:/data

    cli:
        container_name: slide_merger_cli
        image: docker.io/nicolasgrosjean38/slide_merger_cli:0.0.1
        depends_on:
          - backend
        environment:
          - API_BASE_URL=http://backend:8899
        networks:
          - backend_network
        volumes:
          - ./cli/settings.yaml:/app/settings.yaml

networks:
    backend_network:
