---
api:
    # host: 0.0.0.0 # Docker container
    host: localhost # Running locally
    port: 8899
    hide_fastapi_docs: false
log_level: INFO
root_data_directory: ./data
slides:
  - subdirectory: slide_parts/part1
    name_filter: part1
    placeholder: placeholder
